# Generated by Django 4.2 on 2023-04-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_remove_question_pub_date_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='pr',
            field=models.BooleanField(default=False, verbose_name='Правильно'),
        ),
    ]
