# Generated by Django 4.2 on 2023-04-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0004_alter_test_options_remove_choice_votes_choice_pr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Учасник', 'verbose_name_plural': 'Учасники'},
        ),
    ]
