# Generated by Django 4.2 on 2023-04-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_person_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
